---
- name: Install Sonar PHP plugin.
  get_url: >
    url={{ sonar_php_plugin_url }}
    dest=/usr/local/sonar/extensions/plugins/{{ sonar_php_plugin_jar }}
  notify: restart sonar

- name: Wait for Sonar to start.
  wait_for: port=9000 delay=30

- name: Check if Sonar's database is already configured correctly.
  shell: >
    mysql -u {{ sonar_mysql_user }} -p{{ sonar_mysql_password }} {{ sonar_mysql_database }} -e
    "SELECT COUNT(*) FROM properties WHERE text_value='Drupal 7'"
  register: sonar_setup
  changed_when: false
  failed_when: false

- name: Wait for Sonar to start (again).
  wait_for: port=9000 delay=30
  when: "'0' in sonar_setup.stdout"

- name: Copy Sonar database provisioning scripts to temp directory.
  copy: >
    src={{ item }}
    dest=/tmp/{{ item }}
  when: "'0' in sonar_setup.stdout"
  with_items:
    - sonar-php-custom-rules.sql
    - sonar-php-profile-setup.sql

# Add in Drupal custom rulesets (if using v1.2 of plugin).
# See: http://jira.codehaus.org/browse/SONARPHP-270 (for v2.x).
- name: Set up Sonar MySQL database.
  shell: >
    mysql -u {{ sonar_mysql_user}} -p{{ sonar_mysql_password }} {{ sonar_mysql_database }}
    < /tmp/sonar-php-custom-rules.sql
  when: "'0' in sonar_setup.stdout"

- name: Restart Sonar to pick up new rules.
  service: name=sonar state=restarted
  when: "'0' in sonar_setup.stdout"

- name: Wait for Sonar to start (again).
  wait_for: port=9000 delay=30
  when: "'0' in sonar_setup.stdout"

- name: Set up Sonar MySQL database (again).
  shell: >
    mysql -u {{ sonar_mysql_user}} -p{{ sonar_mysql_password }} {{ sonar_mysql_database }}
    < /tmp/sonar-php-profile-setup.sql
  when: "'0' in sonar_setup.stdout"
